# Site settings
title: Yvette Aban

#description: 'Yvette Aban's portfolio site and blog.'
#url: "https://yvetteaban.com" # the base hostname & protocol for your site
#baseurl: "" # the subpath of your site, e.g. /blog/

instagram_username: yvetteaban
github_username:  yvetteaban
linkedin_username:  yvetteaban
email: hello@yvetteaban.com

comments: true

# Build settings
markdown: kramdown