# Site settings
title: Yvette Aban | Front-end Developer
#email: yvette@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   This is Yvette's portfolio site.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yvetteaban.com" # the base hostname & protocol for your site
twitter_username: yvetteaban
github_username:  yvetteaban

# Build settings
markdown: kramdown
